# Generated by Django 6.1.1 on 2026-09-23 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_token', models.CharField(blank=True, db_index=True, help_text='Associated guest session token if unauthenticated guest', max_length=64, null=True)),
                ('registration_token', models.CharField(db_index=True, help_text='Firebase Cloud Messaging device token', max_length=255, unique=True)),
                ('device_id', models.CharField(blank=True, help_text='Unique hardware/app device ID', max_length=255)),
                ('device_type', models.CharField(blank=True, default='android', help_text='ios, android, web, etc.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCM device token',
                'verbose_name_plural': 'FCM device tokens',
                'ordering': ['-updated_at'],
            },
        ),
    ]
