# Generated by Django 6.1.1 on 2026-09-23 17:39

import apps.porchlights.models
import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default=apps.porchlights.models.generate_invitation_code, max_length=64, unique=True)),
                ('invited_email', models.EmailField(blank=True, help_text='Optional target email address for recipient', max_length=254, null=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('GUEST', 'Guest')], default='GUEST', max_length=20)),
                ('is_guest', models.BooleanField(default=False, help_text='True if this invitation provides instant guest access without requiring an account')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Maximum number of uses allowed (0 for unlimited)')),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration timestamp', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_token', models.CharField(db_index=True, default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('guest_name', models.CharField(default='Guest', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_sessions', to='porchlights.invitation')),
            ],
            options={
                'verbose_name': 'guest session',
                'verbose_name_plural': 'guest sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Porchlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name of the porchlight', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional location or description')),
                ('is_on', models.BooleanField(default=False)),
                ('brightness', models.PositiveSmallIntegerField(default=100, help_text='Brightness percentage (0-100)')),
                ('color', models.CharField(default='#FFD54F', help_text='Hex or CSS color code', max_length=30)),
                ('status_message', models.CharField(blank=True, help_text='Optional custom status or notice', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_porchlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'porchlight',
                'verbose_name_plural': 'porchlights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='porchlight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='porchlights.porchlight'),
        ),
        migrations.CreateModel(
            name='PorchlightMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('GUEST', 'Guest')], default='MEMBER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('porchlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='porchlights.porchlight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porchlight_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'porchlight member',
                'verbose_name_plural': 'porchlight members',
                'ordering': ['-created_at'],
                'unique_together': {('porchlight', 'user')},
            },
        ),
    ]
