# Generated by Django 6.1.1 on 2026-09-24 00:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchlights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='guest_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='numeric_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='porchlight',
            name='active_duration',
            field=models.IntegerField(default=4, help_text='Active duration in hours'),
        ),
        migrations.AddField(
            model_name='porchlight',
            name='active_until',
            field=models.DateTimeField(blank=True, help_text='Active expiration timestamp', null=True),
        ),
        migrations.AddField(
            model_name='porchlight',
            name='location',
            field=models.TextField(blank=True, help_text='Optional location or coordinates', null=True),
        ),
        migrations.AddField(
            model_name='porchlight',
            name='type',
            field=models.CharField(default='default', help_text='Type of beacon/porchlight', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='porchlight',
            name='description',
            field=models.TextField(blank=True, help_text='Optional location description'),
        ),
        migrations.AlterField(
            model_name='porchlight',
            name='name',
            field=models.CharField(help_text='Friendly name of the porchlight or beacon', max_length=255),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_id', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to='porchlights.invitation')),
                ('porchlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='porchlights.porchlight')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('porchlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='porchlights.porchlight')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
