# Generated by Django 6.1.1 on 2026-09-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchlights', '0002_invitation_guest_token_invitation_numeric_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porchlight',
            name='location',
            field=models.JSONField(blank=True, help_text='Geocoordinates (e.g. {"latitude": float, "longitude": float}) or location data', null=True),
        ),
    ]
