# Generated by Django 6.1.1 on 2026-09-28 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porchlights', '0005_porchlight_numeric_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='type',
        ),
    ]
