# Generated by Django 6.1.1 on 2026-09-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchlights', '0006_remove_rsvp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
