# Generated by Django 6.1.1 on 2026-10-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchlights', '0007_permission_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porchlight',
            name='type',
            field=models.CharField(default='virtual', help_text='Type of beacon/porchlight', max_length=100),
        ),
    ]
