# Generated by Django 6.1.1 on 2026-10-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porchlights', '0008_alter_porchlight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
