# Generated by Django 6.1.1 on 2026-10-07 03:17

from django.conf import settings
from django.db import migrations, models


def seed_numeric_id_allocators(apps, schema_editor):
    NumericIdAllocator = apps.get_model('porchlights', 'NumericIdAllocator')
    Porchlight = apps.get_model('porchlights', 'Porchlight')
    Invitation = apps.get_model('porchlights', 'Invitation')
    for key, model in (('porchlight', Porchlight), ('invitation', Invitation)):
        maximum = model.objects.aggregate(maximum=models.Max('numeric_id'))['maximum'] or 0
        NumericIdAllocator.objects.create(key=key, next_value=maximum + 1)


class Migration(migrations.Migration):

    dependencies = [
        ('porchlights', '0009_permission_is_close'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericIdAllocator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'numeric ID allocator',
                'verbose_name_plural': 'numeric ID allocators',
            },
        ),
        migrations.RunPython(seed_numeric_id_allocators, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('porchlight', 'user'), name='unique_user_permission_per_porchlight'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_id__isnull', False)), fields=('porchlight', 'guest_id'), name='unique_guest_permission_per_porchlight'),
        ),
        migrations.AddConstraint(
            model_name='rsvp',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('porchlight', 'user'), name='unique_user_rsvp_per_porchlight'),
        ),
        migrations.AddConstraint(
            model_name='rsvp',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_id__isnull', False)), fields=('porchlight', 'guest_id'), name='unique_guest_rsvp_per_porchlight'),
        ),
    ]
