# Generated by Django 6.1.1 on 2026-10-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porchlights', '0010_numericidallocator_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='permission',
            name='unique_user_permission_per_porchlight',
        ),
        migrations.RemoveConstraint(
            model_name='permission',
            name='unique_guest_permission_per_porchlight',
        ),
    ]
