# Generated by Django 6.1.1 on 2026-10-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porchlights', '0005_replace_location_with_pointfield'),
        ('porchlights', '0011_remove_permission_unique_user_permission_per_porchlight_and_more'),
    ]

    operations = [
    ]
